/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHead: (typeof import('./components/AppHead.vue'))['default']
    BaseHeader: (typeof import('./components/BaseHeader.vue'))['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    Header: (typeof import('./components/Header.vue'))['default']
    Logs: typeof import('./components/Logs.vue')['default']
    LogsDisplay: (typeof import('./components/LogsDisplay.vue'))['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    Settings: typeof import('./components/Settings.vue')['default']
    Status: typeof import('./components/Status.vue')['default']
    Test: (typeof import('./components/Test.vue'))['default']
  }
}
